name: 'newsapi'
version: '1.0.0'
config-version: 2

profile: 'dwh-motherduck'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dwh-motherduck:
    staging:
      +materialized: view
    marts:
      +materialized: table
