on:
  workflow_dispatch: {}
  push:
    branches:
      - main

permissions:
    id-token: write   
    contents: write 
    deployments: write

jobs:
  dbt-build-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/python-dbt-setup
        with:
          aws-role: arn:aws:iam::966634658127:user/datadidact_admin
      - name: check DBT source freshness
        run: pipenv run dbt source freshness
      - name: run DBT 
        run: pipenv run dbt build --store-failures
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dbt-artifacts
          path: target/
  
